export enum ActionTypesConvert {
    FETCH_CONVERT = 'FETCH_CONVERT', 
    SET_FROM_CURRENCY = 'SET_FROM_CURRENCY',
    SET_TO_CURRENCY = 'SET_TO_CURRENCY',
    SET_AMOUNT = "SET_AMOUNT",
    SET_SWAP_CURRENCY="SET_SWAP_CURRENCY"
}

export enum ActionTypesHistory {
    SET_HISTORY_CURRENCY = "SET_HISTORY_CURRENCY",
    SET_HISTORY_DATE = "SET_HISTORY_DATE",
    FETCH_HISTORY_DATA = "FETCH_HISTORY_DATA"
}

export enum ActionTypesComparison {
    SET_COMPARISON_BASE_CURRENCY = "SET_COMPARISON_BASE_CURRENCY",
    SET_COMPARISON_CURRENT_CURRENCY = "SET_COMPARISON_CURRENT_CURRENCY",
    SET_COMPARISON_RANGE_DATE = "SET_COMPARISON_RANGE_DATE",
    SET_COMPARISON_RESPONSE = "SET_COMPARISON_RESPONSE"
}

export enum ActionTypesChart {
    SET_CHART_BASE_CURRENCY = "SET_CHART_BASE_CURRENCY",
    SET_CHART_CURRENT_CURRENCY = "SET_CHART_CURRENT_CURRENCY",
    SET_CHART_RANGE_DATE = "SET_CHART_RANGE_DATE",
    SET_CHART_RESPONSE = "SET_CHART_RESPONSE"
}
