export enum ActionTypes {
    FETCH_CONVERT = 'FETCH_CONVERT', 
    SET_FROM_CURRENCY = 'SET_FROM_CURRENCY',
    SET_TO_CURRENCY = 'SET_TO_CURRENCY',
    SET_AMOUNT = "SET_AMOUNT",
    SET_SWAP_CURRENCY="SET_SWAP_CURRENCY"
}
